spring:
  application:
    name: hr-service

  datasource:
    url: jdbc:mysql://centerbeam.proxy.rlwy.net:56024/railway
    username: root
    password: uTdHtgdIQitzGtGYcIAUrAjDDreTqqDU
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000 # 5 minutes
      max-lifetime: 1800000 # 30 minutes
      connection-timeout: 30000 # 30 seconds
      pool-name: MasterHikariPool

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: sendtosankar@gmail.com
    password: apsg dsyc izdh yrht
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8085

logging:
  level:
    com.zen.notify: DEBUG
    com.netflix: ERROR
  file:
    name: logs/hr-debug.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] [%X{sessionId}] %-5level %logger{36} - %msg%n"
